webtalk_init -webtalk_dir /home/zhengyuanbo/project/xilinx/dma/noDDRtest/noDDRtest.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-11-16 18:05:30" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ijdpqrad5qt9hesn7hq7i5sf8l" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3286.064 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.038 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1542361727000" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1542361727000"
webtalk_add_data -client sdk -key uid -value "1542361816000" -context "sdk\\\\bsp/1542361816000"
webtalk_add_data -client sdk -key hwid -value "1542361727000" -context "sdk\\\\bsp/1542361816000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1542361816000"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\bsp/1542361816000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1542361816000"
webtalk_add_data -client sdk -key uid -value "1542361819000" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key hwid -value "1542361727000" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key bspid -value "1542361816000" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key projSize -value "396.8515625" -context "sdk\\\\application/1542361819000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1542362730680"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1542362730680"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1542362730680"
webtalk_add_data -client sdk -key DebugCount -value "5" -context "sdk\\\\bsp/1542362730680"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1542362730680"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1542362730680"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1542362730680"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1542362730680"
webtalk_transmit -clientid 3593312715 -regid "" -xml /home/zhengyuanbo/project/xilinx/dma/noDDRtest/noDDRtest.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/zhengyuanbo/project/xilinx/dma/noDDRtest/noDDRtest.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/zhengyuanbo/project/xilinx/dma/noDDRtest/noDDRtest.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
